
def throw_exce(request):
    raise Exception("break on purpose")
